name: wechat_assets_picker
description: An assets' picker written in pure Dart which looks like the one in WeChat, support multi asset pick from the device.
version: 3.0.0+1
homepage: https://github.com/fluttercandies/flutter_wechat_assets_picker

environment:
  sdk: ">=2.8.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.5.8+2
  extended_image: ^0.9.0
  flutter_common_exports: ^0.1.0
  path_provider: ^1.6.11
  photo_manager: ^0.5.6
  provider: ^4.3.1
  video_player: ^0.10.11+2
